// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

interface IRewardDistributor {
    
    // Events for claim and root update tracking
    event ClaimProcessed(address indexed recipient, uint256 amount);
    event MerkleRootUpdated(bytes32 indexed oldRoot, bytes32 indexed newRoot);
    event DoubleClaimAttempted(address indexed recipient);

    // the name of the struct here is Claim
    // and the fields here are recipient(the datatype is address) that the person that to claim 
    // the amount to be claimed from the treasury
    // proof which means that the existing user exist in the approved distribution and the correct amount being demanded is the correct amount that was 
    // allocated to the user
    struct Claim {
        address recipient;    
        uint256 amount;       
        bytes32[] proof;      
    }

    // and the fields here are recipient(the datatype is address) that the person that to claim 
    // the amount to be claimed from the treasury
    // proof which means that the existing user exist in the approved distribution and the correct amount being demanded is the correct amount that was 
    // allocated to the user
    // Reverts if recipient already claimed (prevents double claim)
    function claim(
        address recipient,
        uint256 amount,
        bytes32[] calldata proof
    ) external;

    
    // now the user address is passed as an input and denoted as recipient 
    // if it true or false that why it in a boolean state
    function hasClaimed(address recipient) external view returns (bool);

    
    // now if it to distibuted newly
    // it has to be updated newly 
    // the new root is gotten from the merkle tree that stored onchain
    // Only callable by governance/admin (access control enforced in implementation)
    // Allows root updates without breaking in-flight claims
    function updateMerkleRoot(bytes32 newRoot) external;

    // Get current Merkle root
    // now does this get a newMerkle root that was generated by the merkle tree or what
    function getMerkleRoot() external view returns (bytes32);

    
    // a function to get the tokens that has not been claimed yet
    function getTotalUnclaimed() external view returns (uint256);

    // Get list of all recipients (paginated)
    function getRecipients(uint256 offset, uint256 limit) external view returns (address[] memory);

    // Get total recipients count
    function getRecipientCount() external view returns (uint256);

    // Get claim amount for a specific recipient (with proof verification)
    // Requires amount parameter for merkle proof verification
    // Returns the verified amount if proof is valid, 0 otherwise
    function getClaimAmount(address recipient, uint256 amount, bytes32[] calldata proof) external view returns (uint256);
}